version: '3.8'
services:
  mysql_db:
    image: mysql:8
    container_name: auth_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: auth_service_db
      MYSQL_USER: xtsulyts
      MYSQL_PASSWORD: avmayo852
    volumes:
      - mysql_auth_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
      interval: 5s

  auth_service:
    build: ./auth_services
    container_name: auth_service
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: mysql_db
      DB_NAME: auth_service_db
      DB_USER: xtsulyts
      DB_PASSWORD: avmayo852
      JWT_SECRET: "tu_super_secreto_jwt_min_32_caracteres"
      JWT_EXPIRES_IN: "7d"
      BCRYPT_ROUNDS: "12"
      EMAIL_USER: "531xsulyts@gmail.com"
      EMAIL_PASS: "wjaxhhpvuvftwdfd"
    ports:
      - "3001:3001"
    depends_on:
      mysql_db:
        condition: service_healthy  # Espera a que la DB esté lista

  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      NODE_ENV: development
      PORT: 3000
      USER_SERVICE_URL: http://auth_service:3001  # ¡CRÍTICO! Nombre del servicio
    ports:
      - "3000:3000"  # El gateway expone el puerto 3000
    depends_on:
      - auth_service  # Espera a que auth_service esté listo

volumes:
  mysql_auth_data: